<a href="https://colab.research.google.com/github/GabrielCondori22/GabrielCondori22/blob/main/prac_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
# Importamos la libreria numpy de python
import numpy as np

In [15]:
# 1. Creación de Arrays:

# Crear un array unidimensional (vector) con 5 elementos enteros de mi elección.
vector = np.array([1, 2, 3, 4, 5])

# Crear una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
matriz_consecutivos = np.arange(1, 10).reshape(3, 3)

# Utilizar la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
matriz_zeros = np.zeros((2, 4), dtype=int)

# Utilizar la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
matriz_unos = np.ones((3, 2), dtype=int)

# Utilizar la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.
matriz_aleatoria = np.random.randint(0, 11, (4, 4))

# Imprimir los resultados
print("Vector:", vector)
print("Matriz de valores consecutivos:\n", matriz_consecutivos)
print("Matriz de ceros:\n", matriz_zeros)
print("Matriz de unos:\n", matriz_unos)
print("Matriz aleatoria:\n", matriz_aleatoria)

Vector: [1 2 3 4 5]
Matriz de valores consecutivos:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz de ceros:
 [[0 0 0 0]
 [0 0 0 0]]
Matriz de unos:
 [[1 1]
 [1 1]
 [1 1]]
Matriz aleatoria:
 [[ 1  8  5 10]
 [ 4  3  6  0]
 [ 9  4  6  7]
 [ 4  6  1 10]]


In [16]:
# 2. Acceso a Elementos:

# Acceder al tercer elemento del vector creado anteriormente.
tercer_elemento_vector = vector[2]

# Acceder al elemento en la segunda fila y segunda columna de la matriz creada anteriormente.
elemento_segunda_fila_segunda_columna = matriz_consecutivos[1, 1]

# Imprimir los resultados
print("Tercer elemento del vector:", tercer_elemento_vector)
print("Elemento en la segunda fila y segunda columna de la matriz:", elemento_segunda_fila_segunda_columna)


Tercer elemento del vector: 3
Elemento en la segunda fila y segunda columna de la matriz: 5


In [17]:
# 3. Propiedades de los Arrays:

# Utilizar el atributo ndim para verificar la cantidad de dimensiones de la matriz creada anteriormente.
dimensiones_matriz = matriz_consecutivos.ndim

# Utilizar el atributo shape para obtener la forma de la matriz creada anteriormente.
forma_matriz = matriz_consecutivos.shape

# Utilizar el atributo size para obtener el tamaño total de la matriz creada anteriormente.
tamaño_matriz = matriz_consecutivos.size

# Imprimir los resultados
print("Cantidad de dimensiones de la matriz:", dimensiones_matriz)
print("Forma de la matriz:", forma_matriz)
print("Tamaño total de la matriz:", tamaño_matriz)


Cantidad de dimensiones de la matriz: 2
Forma de la matriz: (3, 3)
Tamaño total de la matriz: 9


In [18]:
# 4. Operaciones Básicas:

# Sumar dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
matriz1 = np.random.randint(0, 11, (2, 2))
matriz2 = np.random.randint(0, 11, (2, 2))
suma_matrices = matriz1 + matriz2

# Multiplicar dos matrices de tamaño 3x2 y 2x3 respectivamente.
matriz3 = np.random.randint(0, 11, (3, 2))
matriz4 = np.random.randint(0, 11, (2, 3))
producto_matrices = np.dot(matriz3, matriz4)

# Dividir una matriz de tamaño 2x2 por otra matriz de tamaño 2x2, utilizando tanto la división por elementos como la multiplicación por la inversa.
matriz5 = np.random.randint(1, 11, (2, 2))
matriz6 = np.random.randint(1, 11, (2, 2))

# División por elementos
division_elementos = matriz5 / matriz6

# Multiplicación por la inversa
inversa_matriz6 = np.linalg.inv(matriz6)
division_inversa = np.dot(matriz5, inversa_matriz6)

# Imprimir los resultados
print("Suma de matrices:\n", suma_matrices)
print("\nProducto de matrices:\n", producto_matrices)
print("\nDivisión por elementos:\n", division_elementos)
print("\nMultiplicación por la inversa:\n", division_inversa)


Suma de matrices:
 [[15 18]
 [14  1]]

Producto de matrices:
 [[ 18 100  78]
 [ 12  40   4]
 [ 15  80  59]]

División por elementos:
 [[2.         1.5       ]
 [0.33333333 1.25      ]]

Multiplicación por la inversa:
 [[ 1.1  0.2]
 [ 3.3 -0.4]]


In [21]:
# 5. Manipulación de Arrays:

# Crear un array unidimensional (vector) con 5 elementos enteros de mi elección
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Utilizar la función reshape() para convertir el vector en una matriz de tamaño 1x9
matriz_1x9 = vector.reshape(1, 9)

# Utilizar la función flatten() para convertir la matriz en un vector unidimensional
vector_unidimensional = matriz_1x9.flatten()

# Imprimir los resultados
print("Matriz 1x9:\n", matriz_1x9)
print("\nVector unidimensional:\n", vector_unidimensional)


Matriz 1x9:
 [[1 2 3 4 5 6 7 8 9]]

Vector unidimensional:
 [1 2 3 4 5 6 7 8 9]


In [23]:
# 6. Operaciones Estadísticas:

# Matriz creada en el ejercicio "Acceso a Elementos"
matriz_consecutivos = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calcula la suma de todos los elementos de la matriz
suma_total = np.sum(matriz_consecutivos)

# Calcula la media de cada fila de la matriz
media_filas = np.mean(matriz_consecutivos, axis=1)

# Imprimir los resultados
print("Suma de todos los elementos de la matriz:", suma_total)
print("Media de cada fila de la matriz:", media_filas)


Suma de todos los elementos de la matriz: 45
Media de cada fila de la matriz: [2. 5. 8.]


In [25]:
#7. Indexación y Rebanado:
# Matriz creada en el ejercicio "Acceso a Elementos"
matriz_consecutivos = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Imprimir la primera fila de la matriz
primera_fila = matriz_consecutivos[0]

# Imprimir las primeras dos columnas de la matriz
primeras_dos_columnas = matriz_consecutivos[:, :2]

# Imprimir los resultados
print("Primera fila de la matriz:", primera_fila)
print("Primeras dos columnas de la matriz:\n", primeras_dos_columnas)


Primera fila de la matriz: [1 2 3]
Primeras dos columnas de la matriz:
 [[1 2]
 [4 5]
 [7 8]]


In [26]:
# 8. Ejercicio Adicional:

# Define una matriz de tamaño 4x4 con valores aleatorios
matriz_aleatoria = np.random.randint(0, 100, (4, 4))

# Encuentra el valor máximo y su posición
valor_maximo = np.max(matriz_aleatoria)
posicion_maximo = np.unravel_index(np.argmax(matriz_aleatoria), matriz_aleatoria.shape)

# Encuentra el valor mínimo y su posición
valor_minimo = np.min(matriz_aleatoria)
posicion_minimo = np.unravel_index(np.argmin(matriz_aleatoria), matriz_aleatoria.shape)

# Imprimir los resultados
print("Matriz aleatoria:\n", matriz_aleatoria)
print("\nValor máximo:", valor_maximo)
print("Posición del valor máximo:", posicion_maximo)
print("\nValor mínimo:", valor_minimo)
print("Posición del valor mínimo:", posicion_minimo)


Matriz aleatoria:
 [[95 75 84 27]
 [21 84 80 98]
 [67 98 38 61]
 [28 73 81 51]]

Valor máximo: 98
Posición del valor máximo: (1, 3)

Valor mínimo: 21
Posición del valor mínimo: (1, 0)
